spring.application.name=msvc-result
server.port=8017

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/results
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URLs de microservicios consumidos via OpenFeign
msvc.match.url=http://localhost:8016
