spring.application.name=msvc-prize
server.port=8019

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:mem:prizes;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.path=/docs/swagger-ui.html

# Registro en Eureka. spring.application.name es el nombre con que queda registrado.
# El gateway lo descubre usando lb://msvc-prize
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.instance.prefer-ip-address=true

# URLs de microservicios consumidos via OpenFeign
msvc.tournament.url=http://localhost:8012
msvc.ranking.url=http://localhost:8018

jwt.secret=clave-secreta-super-segura-para-jwt-esports-arena-manager-2026
