spring.application.name=msvc-ranking
server.port=8018

# Base de datos H2 en archivo
spring.datasource.url=jdbc:h2:file:./data/rankings
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=sa

spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update

# Consola H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# URLs de microservicios consumidos via OpenFeign
msvc.tournament.url=http://localhost:8012
msvc.registration.url=http://localhost:8015
msvc.result.url=http://localhost:8017
